-- 1. Create the transactions table
create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  type character varying not null,
  amount numeric(15, 2) not null,
  category character varying not null,
  date date not null,
  description text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint user_id foreign key(user_id) references auth.users(id) on delete cascade
);

-- 2. Set up Row Level Security (RLS)
-- Enable RLS for the table
alter table public.transactions enable row level security;

-- 3. Create RLS policies
-- TRANSACTIONS table policies
-- Policy: Users can perform all actions (SELECT, INSERT, UPDATE, DELETE) on their own transactions.
create policy "Allow full access for user's own transactions"
on public.transactions for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);